### ISSUE TITLE
Issue with the <functional> header.

### ISSUE THREAD

**Issue by lowlevl** [andysworkshop/avr-stl#4]
Hi,
I'm using AVR-STL and I'm having issues with it.

Here is my configuration:
  * AVR-STL 1.1.1
  * Arduino IDE 1.8.5

This code:
```
#include <functional>

std::function<void()> f;

void setup() {}
void loop() {}
```

Just a simple use of std::function fails and I get an 'undefined type error' which is decribed by the compiler by:
>error: 'function' in namespace 'std' does not name a template type
>
> std::function<void()> f;
>
>      ^
>
>exit status 1
>'function' in namespace 'std' does not name a template type

Maybe you could help me with that ?
I can do a pull-request if needed.

*I also found that `<map>` needs `<iterator>` inclusion before and don't auto-include it.*

Thanks by advance.

**Comment by Nurrl** [comment]
Up !

**Comment by andysworkshop** [comment]
The compiler is correct, `std::function` is not a part of the SGI STL.
