### ISSUE TITLE
I hope the author can set up a License.

### ISSUE THREAD

**Issue by zhengyangliu** [andysworkshop/avr-stl#9]
Hi friend. I would like to be able to reference your code in the project. But you don't have any license set for this repository. This leaves me unsure if I can cite your work. Can you set a license for this repository? Finally, thank you for the help your article has brought me.

**Comment by andysworkshop** [comment]
Fixed (it's the BSD license [also on my website](https://andybrown.me.uk/terms-and-conditions/))
